"use client";
import {useMemo,useState} from "react";
type Item={id:string;title:string;source:string;sourceType:string;publishedAt:string;url:string;primaryCategory:string;regions:string[];audiences:string[];timeHorizon:string;sentiment:"正面"|"中性"|"負面";confidence:"高"|"中"|"低";importance:string;involvesPolicy:boolean;needsReview:boolean;oneLine:string;summary:string;corePoints:string[];marketImpact:string;buyerImpact:string;sellerImpact:string;agentAction:string;numberSources:{claim:string;sourceUrl:string}[]};
type Report={edition:string;updatedAt:string;nextRun:string;items:Item[];buyer:{headline:string;opening:string;points:string[];cta:string};seller:{headline:string;opening:string;points:string[];cta:string}};
const policyWarning="實際適用條件仍應以主管機關、金融機構、地政士或專業人士最新公告與個案審核為準。";
export default function Dashboard({report}:{report:Report}){
 const [audience,setAudience]=useState<"buyer"|"seller">("buyer"),[category,setCategory]=useState("全部"),[copied,setCopied]=useState(false),[open,setOpen]=useState<string|null>(report.items[0]?.id||null);
 const script=report[audience],categories=["全部",...Array.from(new Set(report.items.map(x=>x.primaryCategory)))],items=useMemo(()=>report.items.filter(x=>category==="全部"||x.primaryCategory===category),[category,report.items]);
 const copy=async()=>{await navigator.clipboard.writeText([script.headline,script.opening,...script.points,script.cta].join("\n\n"));setCopied(true);setTimeout(()=>setCopied(false),1500)};
 return <main><header className="top"><a className="brand" href="#"><span>謙仁團隊</span><small>TAIWAN HOUSING INTELLIGENCE</small></a><div className="header-actions"><a href="/admin">來源與關鍵字後台</a><div className="schedule"><i/>每週一・三・五自動更新</div></div></header>
 <section className="hero"><div><p className="eyebrow">AI 房市情報週報</p><h1>把新聞，變成<br/><em>有依據的成交對話。</em></h1><p className="lead">每則情報都有影響標籤與原始來源；數字可追溯，政策不過度推論。</p></div><aside><small>本期情報</small><b>{report.edition}</b><span>更新 {report.updatedAt}</span><div><strong>{report.items.length}</strong><small>正式收錄</small></div><div><strong>{new Set(report.items.map(x=>x.source)).size}</strong><small>引用來源</small></div><p>下次更新：{report.nextRun}</p></aside></section>
 <section className="workspace"><div className="section-head"><div><small>01 / 客戶說帖</small><h2>一鍵切換溝通角度</h2></div><button onClick={copy}>{copied?"已複製":"複製整份說帖"}</button></div><div className="switch"><button className={audience==="buyer"?"active":""} onClick={()=>setAudience("buyer")}>買方版</button><button className={audience==="seller"?"active":""} onClick={()=>setAudience("seller")}>賣方版</button></div><article className="talk"><div className="talk-label">{audience==="buyer"?"BUYER BRIEF｜買方溝通版":"SELLER BRIEF｜賣方溝通版"}</div><h3>{script.headline}</h3><p className="opening">{script.opening}</p><ol>{script.points.map((p,i)=><li key={p}><span>0{i+1}</span><p>{p}</p></li>)}</ol><blockquote>{script.cta}</blockquote></article></section>
 <section className="news"><div className="section-head"><div><small>02 / 房市情報庫</small><h2>每一則判讀都能回到來源</h2></div></div><div className="filters">{categories.map(x=><button key={x} className={category===x?"active":""} onClick={()=>setCategory(x)}>{x}</button>)}</div><div className="cards detailed">{items.map(item=><article className="card" key={item.id}><button className="card-main" onClick={()=>setOpen(open===item.id?null:item.id)} aria-expanded={open===item.id}><div className="card-top"><span>{item.primaryCategory}</span><b>{item.confidence}可信度</b></div><h3>{item.oneLine}</h3><p>{item.title}</p><div className="tags">{item.regions.map(x=><i key={x}>{x}</i>)}{item.audiences.map(x=><i key={x}>{x}</i>)}<i>{item.timeHorizon}</i><i className={`sentiment ${item.sentiment}`}>{item.sentiment}</i>{item.involvesPolicy&&<i>法規／政策</i>}{item.needsReview&&<i className="review">需人工確認</i>}</div></button>{open===item.id&&<div className="detail"><section><h4>新聞摘要</h4><p>{item.summary}</p></section><section><h4>三項核心重點</h4><ol>{item.corePoints.map(x=><li key={x}>{x}</li>)}</ol></section><div className="impact-grid"><section><h4>對房市</h4><p>{item.marketImpact}</p></section><section><h4>對買方</h4><p>{item.buyerImpact}</p></section><section><h4>對賣方</h4><p>{item.sellerImpact}</p></section><section><h4>房仲行動</h4><p>{item.agentAction}</p></section></div>{item.involvesPolicy&&<p className="warning">{policyWarning}</p>}<section><h4>重要數字與原始資料</h4>{item.numberSources.length?item.numberSources.map(x=><a className="citation" href={x.sourceUrl} target="_blank" rel="noreferrer" key={x.claim}>{x.claim}<span>開啟來源 ↗</span></a>):<p>本則未引用重要數字。</p>}<a className="source-link" href={item.url} target="_blank" rel="noreferrer">原始新聞：{item.source}・{item.publishedAt} ↗</a></section></div>}</article>)}</div></section>
 <section className="policy-box"><small>03 / 編輯防線</small><h2>低相關內容不發布，政策資訊強制警語</h2><p>疑似廣告、低相關或無法確認來源的內容只進人工審核區；草案不得寫成已實施，媒體推測不得寫成確定事實，任何漲跌與獲利都不做保證。</p></section><footer className="footer"><b>謙仁團隊・房市情報室</b><span>{policyWarning}</span></footer></main>
}
