import fs from "node:fs/promises";
import path from "node:path";
const root=path.resolve(import.meta.dirname,".."), out=path.join(root,"data","latest.json");
const queries=["台灣 房市","房貸 央行 台灣","實價登錄 房價","不動產 稅制 台灣"];
const clean=s=>s.replace(/<!\[CDATA\[|\]\]>/g,"").replace(/<[^>]+>/g," ").replace(/&amp;/g,"&").replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g," ").trim();
const tag=(b,n)=>clean(b.match(new RegExp(`<${n}[^>]*>([\\s\\S]*?)<\\/${n}>`))?.[1]||"");
const normalized=s=>s.replace(/[｜|].*$/," ").replace(/[\s\p{P}\p{S}]/gu,"").toLowerCase();
const similarity=(a,b)=>{const A=new Set([...normalized(a)]),B=new Set([...normalized(b)]),n=[...A].filter(x=>B.has(x)).length;return n/Math.max(1,new Set([...A,...B]).size)};
const category=t=>/房貸|央行|青安|利率|補貼/.test(t)?"policy":/稅|法規|囤房/.test(t)?"tax":/台北|新北|桃園|新竹|台中|台南|高雄|區域/.test(t)?"regional":"market";
async function collect(){const found=[];for(const q of queries){const url=`https://news.google.com/rss/search?q=${encodeURIComponent(q+" when:7d")}&hl=zh-TW&gl=TW&ceid=TW:zh-Hant`;const xml=await fetch(url,{headers:{"user-agent":"ChienrenHousingBrief/1.0"}}).then(r=>{if(!r.ok)throw new Error(`RSS ${r.status}`);return r.text()});for(const item of xml.match(/<item>[\s\S]*?<\/item>/g)||[]){const title=tag(item,"title"),url=tag(item,"link"),source=tag(item,"source"),date=new Date(tag(item,"pubDate"));if(!title||!url||Number.isNaN(+date)||found.some(x=>similarity(x.title,title)>.72))continue;found.push({id:Buffer.from(url).toString("base64url").slice(0,12),title,source:source||"新聞來源",publishedAt:new Intl.DateTimeFormat("zh-TW",{timeZone:"Asia/Taipei",year:"numeric",month:"2-digit",day:"2-digit"}).format(date),url,category:category(title),summary:"",impact:""})}}return found.slice(0,14)}
const scriptSchema=()=>({type:"object",additionalProperties:false,properties:{headline:{type:"string"},opening:{type:"string"},points:{type:"array",minItems:3,maxItems:3,items:{type:"string"}},cta:{type:"string"}},required:["headline","opening","points","cta"]});
async function rewrite(items,previous){if(!process.env.OPENAI_API_KEY){console.warn("OPENAI_API_KEY 未設定：保留上一期正式內容。");return null}const prompt=`你是台灣房仲市場研究編輯。只依輸入標題與來源整理，不可杜撰數字。刪除重複或低相關項目，保留6至10則；每則寫60字內摘要與45字內顧問觀察。另產生買方、賣方說帖，各含標題、開場、3重點、行動句。繁體中文、務實、不保證漲跌。輸入：${JSON.stringify(items)}`;const schema={type:"object",additionalProperties:false,properties:{items:{type:"array",items:{type:"object",additionalProperties:false,properties:{id:{type:"string"},summary:{type:"string"},impact:{type:"string"},category:{type:"string",enum:["policy","market","regional","tax"]}},required:["id","summary","impact","category"]}},buyer:scriptSchema(),seller:scriptSchema()},required:["items","buyer","seller"]};const res=await fetch(process.env.OPENAI_API_URL||"https://api.openai.com/v1/responses",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${process.env.OPENAI_API_KEY}`},body:JSON.stringify({model:process.env.OPENAI_MODEL||"gpt-5-mini",input:prompt,text:{format:{type:"json_schema",name:"housing_brief",strict:true,schema}}})});if(!res.ok)throw new Error(`AI ${res.status}: ${await res.text()}`);const json=await res.json(),text=json.output_text||json.output?.flatMap(x=>x.content||[]).find(x=>x.type==="output_text")?.text,ai=JSON.parse(text),map=new Map(items.map(x=>[x.id,x]));return {...previous,items:ai.items.map(x=>({...map.get(x.id),...x})).filter(x=>x.title),buyer:ai.buyer,seller:ai.seller}}
const previous=JSON.parse(await fs.readFile(out,"utf8")), report=await rewrite(await collect(),previous);if(report){const now=new Date();report.updatedAt=new Intl.DateTimeFormat("zh-TW",{timeZone:"Asia/Taipei",dateStyle:"short",timeStyle:"short",hour12:false}).format(now);report.edition=`${new Intl.DateTimeFormat("zh-TW",{timeZone:"Asia/Taipei",year:"numeric",month:"long"}).format(now)} AI 房市情報`;report.nextRun="下個週一／三／五 08:00";await fs.writeFile(out,JSON.stringify(report,null,2)+"\n");console.log(`已更新 ${report.items.length} 則新聞`)}
