import fs from "node:fs/promises";import path from "node:path";
const root=path.resolve(import.meta.dirname,".."),reportPath=path.join(root,"data","latest.json"),reviewPath=path.join(root,"data","review-queue.json");
async function config(){if(process.env.CONFIG_API_URL){const r=await fetch(process.env.CONFIG_API_URL,{headers:process.env.CONFIG_API_TOKEN?{authorization:`Bearer ${process.env.CONFIG_API_TOKEN}`}:{}});if(!r.ok)throw Error(`Config ${r.status}`);const j=await r.json();return {keywords:j.keywords.filter(x=>x.enabled).map(x=>x.keyword),sources:j.sources.filter(x=>x.enabled)}}return JSON.parse(await fs.readFile(path.join(root,"config","collector-defaults.json"),"utf8"))}
const clean=s=>s.replace(/<!\[CDATA\[|\]\]>/g,"").replace(/<[^>]+>/g," ").replace(/&amp;/g,"&").replace(/\s+/g," ").trim(),tag=(b,n)=>clean(b.match(new RegExp(`<${n}[^>]*>([\\s\\S]*?)<\\/${n}>`))?.[1]||""),norm=s=>s.replace(/[\s\p{P}\p{S}]/gu,"").toLowerCase();
const similar=(a,b)=>{const A=new Set([...norm(a)]),B=new Set([...norm(b)]),n=[...A].filter(x=>B.has(x)).length;return n/Math.max(1,new Set([...A,...B]).size)};
function sourceAllowed(source,sources){const target=norm(source);return sources.some(x=>{const name=norm(typeof x==="string"?x:x.name||"");return name&&(target.includes(name)||name.includes(target))})}
const focusScore=x=>{const hours=(Date.now()-x.timestamp)/36e5,recent=hours<=72?1000:0,national=/央行|內政部|財政部|行政院|全國|政策|信用管制|利率|房貸|移轉棟數|交易量|房價所得比/.test(x.title)?300:0,taichung=/台中|南屯|西屯|北屯|南區|西區|北區|七期|五期|八期|單元二|單元三|十四期|水湳|烏日|太平|大里|沙鹿|清水|梧棲|海線|捷運藍線|捷運綠線/.test(x.title)?250:0;return recent+national+taichung-hours};
async function collect(){const cfg=await config(),queries=[];for(let i=0;i<cfg.keywords.length;i+=8)queries.push(cfg.keywords.slice(i,i+8).join(" OR "));const found=[];for(const days of [3,7]){for(const q of queries){const feed=`https://news.google.com/rss/search?q=${encodeURIComponent(q+` when:${days}d`)}&hl=zh-TW&gl=TW&ceid=TW:zh-Hant`,xml=await fetch(feed,{headers:{"user-agent":"ChienrenHousingBrief/6.0"}}).then(r=>r.text());for(const item of xml.match(/<item>[\s\S]*?<\/item>/g)||[]){const title=tag(item,"title"),url=tag(item,"link"),source=tag(item,"source"),date=new Date(tag(item,"pubDate"));if(!title||!url||!sourceAllowed(source,cfg.sources)||Number.isNaN(+date)||found.some(x=>similar(x.title,title)>.72))continue;found.push({id:Buffer.from(url).toString("base64url").slice(0,12),title,url,source,timestamp:+date,publishedAt:new Intl.DateTimeFormat("zh-TW",{timeZone:"Asia/Taipei"}).format(date)})}}if(found.length>=30)break}found.sort((a,b)=>focusScore(b)-focusScore(a));return {items:found.slice(0,60),allowedSources:cfg.sources.map(x=>typeof x==="string"?x:x.name),updatedAt:new Date().toISOString(),primaryWindowHours:72,fallbackWindowDays:7}}
async function run(){if(!process.env.OPENAI_API_KEY){console.warn("OPENAI_API_KEY 未設定：保留上一期正式內容。");return}const input=await collect(),previous=JSON.parse(await fs.readFile(reportPath,"utf8"));const prompt=`你是台灣房仲團隊的新聞編輯。只能從allowedSources所列且已通過程式篩選的來源選新聞，固定輸出15則。優先選updatedAt往前72小時內發布的新聞；若不足15則，才用7日內新聞補足，7日以外不得採用。主軸以全國政策、全國數據、台中地區為優先。去除重複、廣告與低相關內容。每則輸出 id、summary、policyStatus、buyerTalk、sellerTalk。buyerTalk和sellerTalk各100至220個中文字，要像資深房仲面對客戶自然說明：先說這則新聞代表什麼，再說對客戶可能的影響，最後給一個實際可做的下一步；語氣完整、人性化、口語但不隨便。不得捏造政策、數字或買方，不得保證漲跌、價格或成交，不得製造急迫感。policyStatus只能是「已生效」「尚未生效」「預測／觀察」「不適用」。輸出JSON物件 {items:[...],review:[{id,reason}]}。輸入：${JSON.stringify(input)}`;const r=await fetch(process.env.OPENAI_API_URL||"https://api.openai.com/v1/responses",{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${process.env.OPENAI_API_KEY}`},body:JSON.stringify({model:process.env.OPENAI_MODEL||"gpt-5-mini",input:prompt,text:{format:{type:"json_object"}}})});if(!r.ok)throw Error(`AI ${r.status}`);const j=await r.json(),text=j.output_text||j.output?.flatMap(x=>x.content||[]).find(x=>x.type==="output_text")?.text,result=JSON.parse(text),map=new Map(input.items.map(x=>[x.id,x])),merge=x=>({...map.get(x.id),...x}),now=new Date(),items=(result.items||[]).map(merge).filter(x=>x.title&&x.buyerTalk&&x.sellerTalk);if(items.length!==15)throw Error(`正式新聞必須為15則：${items.length}`);for(const x of items){const age=(+now-x.timestamp)/36e5;if(age>168)throw Error(`新聞超過7日：${x.id}`);if(Array.from(x.buyerTalk).length<100||Array.from(x.sellerTalk).length<100)throw Error(`說帖不足100字：${x.id}`)}previous.items=items;previous.updatedAt=new Intl.DateTimeFormat("zh-TW",{timeZone:"Asia/Taipei",dateStyle:"short",timeStyle:"short",hour12:false}).format(now);previous.nextRun="下個週一／三／五 08:00";await Promise.all([fs.writeFile(reportPath,JSON.stringify(previous,null,2)+"\n"),fs.writeFile(reviewPath,JSON.stringify({updatedAt:previous.updatedAt,items:result.review||[]},null,2)+"\n")]);console.log(`正式收錄 ${previous.items.length} 則`)}
await run();
